# pvc-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec: 
  volumes:
    - name: pod-storage
      persistentVolumeClaim:
        claimName: pvc1 # matches pvc1.yml:metadata.name
  containers:
    - name: busybox-container
      image: busybox:1.30.1
      command: ['sh', '-c', 'while true; do date; sleep 3; done'] # keeps container running
      volumeMounts:
        - mountPath: "/data"
          name: pod-storage 