apiVersion: v1
kind: Service
metadata:
  name: clusterIP-service-1
spec:
  type: ClusterIP
  selector:
    project: myproject 
    # make sure this selector matches the pods you want to serve
  ports:
  - targetPort: 80  # Port listening on the pod
  port: 80          # Port listening on the service