apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: app1
    project: abc 
  ports:
  - targetPort: 80  # Port listening on the pod
    port: 80          # Port listening on the service